name: Build and Deploy

on:
  push:
    branches:
      - main  # Set this to your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js version with NVM
      uses: actions/setup-node@v3
      with:
        node-version: '21.4.0'

    - name: Install dependencies
      run: npm install

    - name: Run build
      run: npm run build

    - name: Deploy to GitHub Pages
      run: npm run deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

